### ISSUE TITLE
Code review: unused module

### ISSUE THREAD

**Issue by cobolbaby** [rueedlinger/vue-connect#30]
https://github.com/rueedlinger/vue-connect/blob/24c4e3c87733201233308b280875d347968a7e5e/vue-connect-api/app/__init__.py#L3

Is the code reserved to replace the global variable cache?

https://github.com/rueedlinger/vue-connect/blob/24c4e3c87733201233308b280875d347968a7e5e/vue-connect-api/app/routes.py#L23-L28

**Comment by rueedlinger** [comment]
I played around with flask and forget to remove that import.

**Comment by cobolbaby** [comment]
Same Question:

https://github.com/rueedlinger/vue-connect/blob/812be6ecbe48a28c901c4f1da21548937d4af171/vue-connect-ui/src/main.js#L3-L4

https://github.com/rueedlinger/vue-connect/blob/812be6ecbe48a28c901c4f1da21548937d4af171/vue-connect-ui/src/plugins/fontawesome.js#L3-L4

**Comment by cobolbaby** [comment]
LGTM.
