### ISSUE TITLE
Code Review: Repeatable code

### ISSUE THREAD

**Issue by cobolbaby** [rueedlinger/vue-connect#31]
The logic of reload operation and request exception handling is highly repetitive. Do you consider encapsulating a method?

Including:
- View(*.vue):
  - reload operation 
- Flask API:
  - request exception handling

**Comment by rueedlinger** [comment]
You absolutely right. There is too much repetitive code and a refactoring is necessary.

**Comment by cobolbaby** [comment]
LGTM.
