### ISSUE TITLE
Code review: Schedule logic

### ISSUE THREAD

**Issue by cobolbaby** [rueedlinger/vue-connect#32]
https://github.com/rueedlinger/vue-connect/blob/24c4e3c87733201233308b280875d347968a7e5e/vue-connect-api/app/routes.py#L363-L368

Is it possible to migrate the schedule logic from route.py to wsgi.py or others to meet the single-responsibility principle?

In addition, I want to clarify how many workers are currently running in gunicorn. Will the multi-process mode affect schedule tasks?

**Comment by rueedlinger** [comment]
You absolutely right, at the moment I'm not quite happy with the scheduler, worker and the cache.  It's a first draft.

**Some of my thoughts**
- I struggled with flask application's context. It was not working as I expected. I went for a simple solution with state as variable.

- I'm thinking about a solution which can work with multiple workers.
    - The scheduler must run as one instance when there are  multiple gunicorn workers
    - How to share state between multiple workers and the scheduler?
    - The solution should fit in one Docker image. So I don't want to have dependencies to another container. (At least at the moment)
  
**How to share states**
- I'm thinking to use [SQLite](https://www.sqlite.org) to share state between workers and scheduler.
 
**Share state between Backend and Frontend**
- I'm not happy with the frontend pooling, so I looked how to do SSE with flask. But found no satisfying solution.
- I was looking at [fastapi](https://fastapi.tiangolo.com/) to move from *wsgi* to *asgi* to support SSE. But I put that on hold at the moment.

**Comment by cobolbaby** [comment]
> How to share state between multiple workers and the scheduler?

Multiple processes can communicate using mmap(shared memory), and SQLite is also one solution.

> The solution should fit in one Docker image. So I don't want to have dependencies to another container. (At least at the moment)

Agree. Currently the application does not need to rely on external components.

> The scheduler must run as one instance when there are multiple gunicorn workers

You can define an exclusive lock in MMAP. Multiple processes can compete for the lock to ensure that only one schedule task is allowed to run at the same time.

> Share state between Backend and Frontend

Does [flask_sse](https://github.com/singingwolfboy/flask-sse) meet the demand?

**Comment by rueedlinger** [comment]
Thanks for the feedback and hints. Will look at MMAP.

**flask_sse** needs Redis. I would prefer a solution which supports SSE directly and runs in one container.  At the moment I want to keep the deployment as simple as possible.

When I have more time I will try to test if it's feasible  to integrate flask_sse and Redis into the current solution.

**Comment by rueedlinger** [comment]
Tasks
- [ ] Refactor vue-connect-api code (Python) into modules. (backend, scheduler)
- [ ] Store shared state in SQLite db

**Comment by cobolbaby** [comment]
- [ ] Save the downtime of the failed connector in the store

**Comment by cobolbaby** [comment]
LGTM.
