### ISSUE TITLE
Display style of the reload button

### ISSUE THREAD

**Issue by cobolbaby** [rueedlinger/vue-connect#33]
It's so weird that the reload button occupies a whole row. 
![2021-02-07 12-23-57屏幕截图](https://user-images.githubusercontent.com/11460848/107136561-68615f00-693f-11eb-808e-fde265e5cb4f.png)

Do you consider migrate it to the route.name section?

https://github.com/rueedlinger/vue-connect/blob/24c4e3c87733201233308b280875d347968a7e5e/vue-connect-ui/src/App.vue#L26-L34

**Comment by cobolbaby** [comment]
By the way, you can add a filter box in the same area.

**Comment by rueedlinger** [comment]
Thanks for the tip. I'm not used with vue.js and bulma. So I wanted to have quick results for a prototype and these tools seems to work well.

Any suggestion or PR is welcome to have a better user experience for the reload button.

**Comment by cobolbaby** [comment]
Ref: https://github.com/ellakan/vue-connect/commit/26dbdd9aeafefb985ee37debb6e2c7a938f5bef9

**Comment by ellakan** [comment]
![vue-connect-ui](https://user-images.githubusercontent.com/36020060/107459407-1879d680-6b91-11eb-8377-f5b0e91a6376.png)

**Comment by rueedlinger** [comment]
@ellakan that looks nice.....
