### ISSUE TITLE
Handle Kafka Connect API downtime

### ISSUE THREAD

**Issue by cobolbaby** [rueedlinger/vue-connect#4]
When the task execution fails, it is best to directly display the time point of the problem and related error stack. 

This also facilitates locating problems and downtime.

**Comment by rueedlinger** [comment]
I have some questions:

- Do you mean to display the failure details (stacktrace) on the main page (status page)? Because the stacktrace is already displayed on the detail page.
- I don't know if there is any possibility to get the  time point (YY/MM/DD HH:MM:SS ) when exactly the failure occurred from the Kafka Connect Rest API. This could be stored in the backend as state (memory), but would be lost when the app restarts.

**Comment by cobolbaby** [comment]
> Do you mean to display the failure details (stacktrace) on the main page (status page)? Because the stacktrace is already displayed on the detail page.

Sorry, I did not notice the new version released recently

>  I don't know if there is any possibility to get the time point (YY/MM/DD HH:MM:SS ) when exactly the failure occurred from the Kafka Connect Rest API. This could be stored in the backend as state (memory), but would be lost when the app restarts.

The API interface cannot return to the downtime. But if the downtime could be cached in the memory as a state value, it is enough to meet the demand, and I still believe in the stability of the service.

**Comment by cobolbaby** [comment]
> the stack information was not printed under abnormal conditions.

Oh, I need to click on the details to view the stack information. 
But I found that the format of the stack information has changed and it looks twisted.

![2021-02-03 13-14-46屏幕截图](https://user-images.githubusercontent.com/11460848/106701565-d47f5280-6621-11eb-86bf-e2a2630251a5.png)

**Comment by cobolbaby** [comment]
> The API interface cannot return to the downtime. But if the downtime could be cached in the memory as a state value, it is enough to meet the demand, and I still believe in the stability of the service.

In this way, the polling needs to be done in the backend. And it is also convenient to expand the alarm function based on this.

**Comment by rueedlinger** [comment]
I created #25 for displaying errors on the main page. I would focus in this issue (rename title?) how we can improve the experience when there is a downtime of Kafka Connect (Connect Rest API).

**Some open questions:**
- This new feature should work with multiple clusters #5 
- How long should the state be cached in the backend
- How should be the behavior in the frontend with action buttons (restart, resume, pause, delete) 
- Pooling in backend and pushing the updates back with a WebSocket?

**Comment by cobolbaby** [comment]
> This new feature should work with multiple clusters #5 

Indeed, the multi-cluster management mode is bound to affect the structure of the page. Taking these factors into consideration as early as possible will avoid the structural adjustment of the page in the later stage.

> How long should the state be cached in the backend

We can define a list type variable for a connector to save the failure status. Initially, the length of the list can only be set to 1, and then consider extending the length of the list according to the needs.

> How should the frontend behave during a downtime regarding the action buttons (restart, resume, pause, delete)

IMO, maintain the status quo for now.

> Pooling in backend and pushing the updates back with a WebSocket?

SSE is also a good choice. I have seen such implementations in some open source projects, such as [akhq](https://github.com/tchiotludo/akhq).
