### ISSUE TITLE
Code Review: docker build

### ISSUE THREAD

**Issue by cobolbaby** [rueedlinger/vue-connect#43]
https://github.com/rueedlinger/vue-connect/blob/b595a4721f80c9a7e1bf9c7384f77e9ccbd21fe4/Dockerfile#L29-L33

Although this way could also work, it will cause confusion. It is recommended to add `&&` or `mkdir -p /dist/api /dist/db`.

https://github.com/rueedlinger/vue-connect/blob/b595a4721f80c9a7e1bf9c7384f77e9ccbd21fe4/Dockerfile#L35-L37

What is the meaning of the `-S` parameter of adduser? I haven't seen such usage before.

In addition, to create a custom user inside the container, it is recommended to explicitly specify the ID of the user and user group to avoid the problem of mounting directory permissions when the container restarts.

https://github.com/rueedlinger/vue-connect/blob/b595a4721f80c9a7e1bf9c7384f77e9ccbd21fe4/rootfs/docker-entrypoint.sh#L8-L10

When the container is restarted, the storage data is reset.

https://github.com/rueedlinger/vue-connect/blob/b595a4721f80c9a7e1bf9c7384f77e9ccbd21fe4/rootfs/docker-entrypoint.sh#L22-L24

Is it for debugging?

**Comment by rueedlinger** [comment]
Thanks for the input, I have fixed them in #46

Option `-S` is used to create system user. In this case the shell is set to `/sbin/nologin`and the account is disabled. So you can not use the account to log in.
