### ISSUE TITLE
SQLite db locks

### ISSUE THREAD

**Issue by rueedlinger** [rueedlinger/vue-connect#44]
**Review current architecture:**
- prevent SQLite db locks which results in HTTP 500 errors (frontend, scheduler)

**Comment by cobolbaby** [comment]
Could multiple processes access the same SQLite db?

**Comment by rueedlinger** [comment]
Yes, from the SQLite FAQ

> **Can multiple applications or multiple instances of the same application access a single database file at the same  time?**
> Multiple processes can have the same database open at the same time. Multiple processes can be doing a SELECT at the same time. But only one process can be making changes to the database at any moment in time, however.
> ...
> When any process wants to write, it must lock the entire database file for the duration of its update. But that normally only takes a few milliseconds. 


https://www.sqlite.org/faq.html

But I'm not 100% happy with the current solution. It's good for the moment but with heavy write operations this approach might not scale. So I created #49
